name: Build Docker Images

on:
  push:

permissions: {}

env:
  REGISTRY: ghcr.io/garbee

jobs:
  build:
    strategy:
      matrix:
        image:
          - runner: ubuntu-24.04
            platform: linux/amd64
            platform-pair: linux-amd64
          - runner: ubuntu-24.04-arm
            platform: linux/arm64/v8
            platform-pair: linux-arm64-v8
        project:
          - name: project-1
            context: ./project-1/devcontainer
            image-name: project-1-devcontainer
        node-version:
          - 20
          - ''
          - 24
    runs-on: ${{ matrix.image.runner }}
    name: Build ${{ matrix.project.name }} for ${{ matrix.image.platform }} (Node ${{ matrix.node-version || 'default' }})
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435 # v3.11.1
        with:
          cache-binary: false
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 # v3.3.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract Docker metadata
        id: docker-metadata
        uses: docker/metadata-action@c1e51972afc2121e065aed6d45c65596fe445f3f # v5.8.0
        with:
          images: "${{ env.REGISTRY }}/${{ matrix.project.image-name }}${{ matrix.node-version && format('-node{0}', matrix.node-version) || '' }}"
      - name: Build and push Docker image
        uses: docker/build-push-action@48aba3b46d1b1fec4febb7c5d0c644b249a11355 # v6.10.0
        with:
          context: ${{ matrix.project.context }}
          platforms: ${{ matrix.image.platform }}
          push: true
          tags: ${{ steps.docker-metadata.outputs.tags }}
          annotations: ${{ steps.docker-metadata.outputs.annotations }}
          labels: ${{ steps.docker-metadata.outputs.labels }}
          cache-from: type=gha,scope=${{ matrix.project.name }}-${{ matrix.image.platform-pair }}${{ matrix.node-version && format('-node{0}', matrix.node-version) || '' }}
          cache-to: type=gha,mode=max,scope=${{ matrix.project.name }}-${{ matrix.image.platform-pair }}${{ matrix.node-version && format('-node{0}', matrix.node-version) || '' }}
          build-args: |
            ${{ matrix.node-version && format('NODE_VERSION={0}', matrix.node-version) || '' }}
