name: Build Docker Images

on:
  push:

permissions: {}

env:
  REGISTRY: ghcr.io/garbee

jobs:
  build:
    strategy:
      matrix:
        image:
          - runner: ubuntu-24.04
            platform: linux/amd64
            platform-pair: linux-amd64
          - runner: ubuntu-24.04-arm64
            platform: linux/arm64
            platform-pair: linux-arm64
        project:
          - name: project-1
            context: ./project-1/devcontainer
            image-name: project-1-devcontainer
    runs-on: ${{ matrix.image.runner }}
    name: Build ${{ matrix.project.name }} for ${{ matrix.image.platform }} Docker Image
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435 # v3.11.1
        with:
          cache-binary: false
      - name: Extract Docker metadata
        id: docker-metadata
        uses: docker/metadata-action@c1e51972afc2121e065aed6d45c65596fe445f3f # v5.8.0
        with:
          images: "${{ env.REGISTRY }}/${{ matrix.project.image-name }}"
      - name: Build Docker image
        uses: docker/build-push-action@48aba3b46d1b1fec4febb7c5d0c644b249a11355 # v6.10.0
        with:
          context: ${{ matrix.project.context }}
          platforms: ${{ matrix.image.platform }}
          push: false
          tags: ${{ steps.docker-metadata.outputs.tags }}
          labels: ${{ steps.docker-metadata.outputs.labels }}
          outputs: type=docker,dest=/tmp/image-${{ matrix.project.name }}-${{ matrix.image.platform-pair }}.tar
      - name: Upload Docker image artifact
        uses: actions/upload-artifact@b4b15b8c7c6ac21ea08fcf65892d2ee8f75cf882 # v4.5.0
        with:
          name: image-${{ matrix.project.name }}-${{ matrix.image.platform-pair }}
          path: /tmp/image-${{ matrix.project.name }}-${{ matrix.image.platform-pair }}.tar
          retention-days: 1
