name: Build Docker Images

on:
  push:

permissions: {}

env:
  REGISTRY: ghcr.io/garbee

jobs:
  build:
    strategy:
      matrix:
        image:
          - runner: ubuntu-24.04
            platform: linux/amd64
            platform-pair: linux-amd64
          - runner: ubuntu-24.04-arm
            platform: linux/arm64
            platform-pair: linux-arm64
        project:
          - name: project-1
            context: ./project-1
            image-name: project-1
        node-version:
          # - 20
          - ''
          # - 24
    runs-on: ${{ matrix.image.runner }}
    name: Build ${{ matrix.project.name }} for ${{ matrix.image.platform }} (Node ${{ matrix.node-version || 'default' }})
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435 # v3.11.1
        with:
          cache-binary: false
          platforms: ${{ matrix.image.platform }}
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef # v3.6.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract Docker metadata
        id: docker-metadata
        uses: docker/metadata-action@c299e40c65443455700f0fdfc63efafe5b349051 # v5.10.0
        env:
          DOCKER_METADATA_ANNOTATIONS_LEVELS: manifest
        with:
          images: "${{ env.REGISTRY }}/${{ matrix.project.image-name }}${{ matrix.node-version && format('-node{0}', matrix.node-version) || '' }}"
          flavor: |
            latest=true
          tags: |
            type=schedule,pattern={{date 'YYYYMMDD-hhmmss'}}
            type=edge,branch=main
            type=sha
      - name: Build and push Docker image
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6.18.0
        with:
          context: ${{ matrix.project.context }}
          platforms: ${{ matrix.image.platform }}
          push: true
          provenance: false
          sbom: false
          tags: ${{ steps.docker-metadata.outputs.tags }}
          labels: ${{ steps.docker-metadata.outputs.labels }}
          annotations: |
            ${{ steps.docker-metadata.outputs.annotations }}
            org.opencontainers.image.description=Per-arch image description for each variant
          outputs: type=image,name=target,annotations.index:org.opencontainers.image.description=My multi-arch image
          build-args: |
            ${{ matrix.node-version && format('NODE_VERSION={0}', matrix.node-version) || '' }}
