name: Clean Dev Images

on:
  schedule:
    - cron: "13 18 * * 5"
  workflow_dispatch:

permissions: {}

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  clean:
    name: Remove Images
    runs-on: ubuntu-slim
    strategy:
      fail-fast: false
      matrix:
        node-version:
          - 20
          - 22
          - 24
        environment:
          - docker-dev
          - docker-pr
    environment:
      name: ${{ matrix.environment }}
    permissions:
      packages: write # Ability to delete packages from GHCR.
      contents: read
    steps:
      - name: Delete Packages
        uses: actions/delete-package-versions@e5bc658cc4c965c472efe991f8beea3981499c55 # v5.0.0
        with:
          package-name: ${{ vars.IMAGE_NAME }}-node.${{ matrix.node-version }}
          package-type: container
          # Try to delete everything. Hard limit of 100 upstream.
          # Should more than 100 ever exist, it'll just need more runs.
          min-versions-to-keep: 0
